import { create } from "zustand";
import { persist } from "zustand/middleware";
import { get as idbGet, set as idbSet, del as idbDel } from "idb-keyval";
import { idbStorage, createDebouncedPersistStorage } from "@/lib/idb-storage";
import { useProjectsListStore } from "./projects-list-store";

export interface TextBlock {
  id: string;
  type: "speech" | "narration" | "sfx";
  /** "ocr" = generated by OCR (not resizable), "manual" = user-created (resizable/draggable). Defaults to "ocr" for backward compat. */
  source?: "ocr" | "manual";
  originalText: string;
  translatedText: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontSize: number;
  /** Rotation angle in degrees. Defaults to 0. */
  rotation?: number;
  /** Font family name. Defaults to "Comic Neue". */
  fontFamily?: string;
  /** Text fill color. Defaults to "#000000". */
  fontColor?: string;
  /** Text alignment: "left" | "center" | "right". Defaults to "center". */
  textAlign?: "left" | "center" | "right";
  /** Line height multiplier. Defaults to 1.2. */
  lineHeight?: number;
  /** Text direction: "horizontal" (LTR/RTL) or "vertical" (top-to-bottom for CJK). Defaults to "horizontal". */
  textDirection?: "horizontal" | "vertical";
  /** Font weight: "normal" or "bold". Defaults to "normal". */
  fontWeight?: "normal" | "bold";
  /** Font style: "normal" or "italic". Defaults to "normal". */
  fontStyle?: "normal" | "italic";
  boundingPoly?: { x: number; y: number }[];
}

export interface InpaintStroke {
  id: string;
  /** Flat array [x0,y0,x1,y1,...] in image-space coordinates. */
  points: number[];
  /** Brush diameter in image-space pixels. */
  brushSize: number;
}

export interface PageState {
  id: string;
  fileName: string;
  originalImageBase64: string;
  cleanedImageBase64: string | null;
  textBlocks: TextBlock[];
  inpaintStrokes: InpaintStroke[];
  ocrCompleted: boolean;
}

interface ProjectState {
  projectId: string | null;
  projectName: string;
  pages: PageState[];
  activePageId: string | null;
  starred: boolean;
  lastEditedAt: number | null;
  createdAt: number | null;
}

interface ProjectActions {
  setProjectName: (name: string) => void;
  addPages: (files: File[]) => Promise<void>;
  removePage: (pageId: string) => void;
  setActivePage: (pageId: string) => void;
  reorderPages: (newOrder: PageState[]) => void;
  updateTextBlock: (
    pageId: string,
    blockId: string,
    updates: Partial<TextBlock>
  ) => void;
  addTextBlocks: (pageId: string, blocks: TextBlock[]) => void;
  removeTextBlock: (pageId: string, blockId: string) => void;
  setPageOcrCompleted: (pageId: string, completed: boolean) => void;
  addInpaintStroke: (pageId: string, stroke: InpaintStroke) => void;
  removeInpaintStroke: (pageId: string, strokeId: string) => void;
  /** Restore a page snapshot (used by undo/redo). Only restores textBlocks & inpaintStrokes. */
  restorePageSnapshot: (
    pageId: string,
    snapshot: { textBlocks: TextBlock[]; inpaintStrokes: InpaintStroke[] }
  ) => void;
  toggleStar: () => void;
  clearProject: () => void;
  importProject: (data: ProjectState) => void;
  exportProject: () => ProjectState;
  // Multi-project actions
  saveCurrentProject: () => Promise<void>;
  createNewProject: () => Promise<void>;
  switchProject: (targetId: string) => Promise<void>;
  deleteProject: (targetId: string) => Promise<void>;
}

export type ProjectStore = ProjectState & ProjectActions;

const MAX_PAGES = 80;
const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

/**
 * Downscale a base64 image to a tiny thumbnail for the projects list.
 * Uses canvas — browser-only.
 */
function createThumbnail(base64: string, maxWidth = 320): Promise<string> {
  if (typeof window === "undefined") return Promise.resolve("");
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const ratio = maxWidth / img.width;
      const canvas = document.createElement("canvas");
      canvas.width = maxWidth;
      canvas.height = Math.round(img.height * ratio);
      const ctx = canvas.getContext("2d")!;
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      resolve(canvas.toDataURL("image/jpeg", 0.7));
    };
    img.onerror = () => resolve("");
    img.src = base64;
  });
}

/** Extract serializable snapshot from state. */
function getSnapshot(state: ProjectState): ProjectState {
  return {
    projectId: state.projectId,
    projectName: state.projectName,
    pages: state.pages,
    activePageId: state.activePageId,
    starred: state.starred,
    lastEditedAt: state.lastEditedAt,
    createdAt: state.createdAt,
  };
}

/** Persist full project data to its own IndexedDB key. */
async function persistProjectToIDB(state: ProjectState): Promise<void> {
  if (!state.projectId) return;
  await idbSet(
    `komakun-project-${state.projectId}`,
    JSON.stringify(getSnapshot(state))
  );
}

/** Sync a lightweight summary to the projects list store. */
async function syncSummaryToList(state: ProjectState): Promise<void> {
  if (!state.projectId) return;
  const thumb = state.pages[0]?.originalImageBase64
    ? await createThumbnail(state.pages[0].originalImageBase64)
    : null;
  useProjectsListStore.getState().upsertProject({
    id: state.projectId,
    name: state.projectName,
    pageCount: state.pages.length,
    thumbnailBase64: thumb,
    starred: state.starred,
    lastEditedAt: state.lastEditedAt,
    createdAt: state.createdAt,
  });
}

const EMPTY_PROJECT: ProjectState = {
  projectId: null,
  projectName: "Untitled Project",
  pages: [],
  activePageId: null,
  starred: false,
  lastEditedAt: null,
  createdAt: null,
};

export const useProjectStore = create<ProjectStore>()(
  persist(
    (set, get) => ({
      // ── State ──
      ...EMPTY_PROJECT,

      // ── Single-project actions ──

      setProjectName: (name) =>
        set({ projectName: name, lastEditedAt: Date.now() }),

      addPages: async (files) => {
        const state = get();
        const remainingSlots = MAX_PAGES - state.pages.length;
        if (remainingSlots <= 0) return;

        const validFiles = files
          .filter((f) => f.type.startsWith("image/") && f.size <= MAX_FILE_SIZE)
          .sort((a, b) =>
            a.name.localeCompare(b.name, undefined, {
              numeric: true,
              sensitivity: "base",
            })
          )
          .slice(0, remainingSlots);

        const newPages: PageState[] = [];
        for (const file of validFiles) {
          newPages.push({
            id: generateId(),
            fileName: file.name,
            originalImageBase64: await fileToBase64(file),
            cleanedImageBase64: null,
            textBlocks: [],
            inpaintStrokes: [],
            ocrCompleted: false,
          });
        }

        const now = Date.now();
        set((s) => ({
          projectId: s.projectId || generateId(),
          pages: [...s.pages, ...newPages],
          activePageId: s.activePageId || newPages[0]?.id || null,
          lastEditedAt: now,
          createdAt: s.createdAt || now,
        }));
      },

      removePage: (pageId) =>
        set((s) => {
          const pages = s.pages.filter((p) => p.id !== pageId);
          const activePageId =
            s.activePageId === pageId ? pages[0]?.id || null : s.activePageId;
          return { pages, activePageId, lastEditedAt: Date.now() };
        }),

      setActivePage: (pageId) => set({ activePageId: pageId }),

      reorderPages: (newOrder) =>
        set({ pages: newOrder, lastEditedAt: Date.now() }),

      toggleStar: () =>
        set((s) => ({ starred: !s.starred })),

      updateTextBlock: (pageId, blockId, updates) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? {
                  ...page,
                  textBlocks: page.textBlocks.map((block) =>
                    block.id === blockId ? { ...block, ...updates } : block
                  ),
                }
              : page
          ),
        })),

      addTextBlocks: (pageId, blocks) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? { ...page, textBlocks: [...page.textBlocks, ...blocks] }
              : page
          ),
          lastEditedAt: Date.now(),
        })),

      removeTextBlock: (pageId, blockId) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? {
                  ...page,
                  textBlocks: page.textBlocks.filter((b) => b.id !== blockId),
                }
              : page
          ),
          lastEditedAt: Date.now(),
        })),

      setPageOcrCompleted: (pageId, completed) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? { ...page, ocrCompleted: completed }
              : page
          ),
        })),

      addInpaintStroke: (pageId, stroke) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? { ...page, inpaintStrokes: [...(page.inpaintStrokes ?? []), stroke] }
              : page
          ),
          lastEditedAt: Date.now(),
        })),

      removeInpaintStroke: (pageId, strokeId) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? {
                  ...page,
                  inpaintStrokes: (page.inpaintStrokes ?? []).filter(
                    (s) => s.id !== strokeId
                  ),
                }
              : page
          ),
          lastEditedAt: Date.now(),
        })),

      restorePageSnapshot: (pageId, snapshot) =>
        set((s) => ({
          pages: s.pages.map((page) =>
            page.id === pageId
              ? {
                  ...page,
                  textBlocks: snapshot.textBlocks,
                  inpaintStrokes: snapshot.inpaintStrokes,
                }
              : page
          ),
          lastEditedAt: Date.now(),
        })),

      clearProject: () => set({ ...EMPTY_PROJECT }),

      importProject: (data) =>
        set({
          projectId: data.projectId,
          projectName: data.projectName,
          pages: data.pages,
          activePageId: data.activePageId,
          starred: data.starred ?? false,
          lastEditedAt: data.lastEditedAt ?? Date.now(),
          createdAt: data.createdAt ?? Date.now(),
        }),

      exportProject: () => {
        const s = get();
        return {
          projectId: s.projectId,
          projectName: s.projectName,
          pages: s.pages,
          activePageId: s.activePageId,
          starred: s.starred,
          lastEditedAt: s.lastEditedAt,
          createdAt: s.createdAt,
        };
      },

      // ── Multi-project actions ──

      saveCurrentProject: async () => {
        const state = get();
        if (!state.projectId) return;
        await persistProjectToIDB(state);
        await syncSummaryToList(state);
      },

      createNewProject: async () => {
        const state = get();
        // Save current project before resetting
        if (state.projectId) {
          await persistProjectToIDB(state);
          await syncSummaryToList(state);
        }
        set({ ...EMPTY_PROJECT });
      },

      switchProject: async (targetId) => {
        const state = get();
        // Save current project first
        if (state.projectId && state.projectId !== targetId) {
          await persistProjectToIDB(state);
          await syncSummaryToList(state);
        }
        // Load target from IndexedDB
        const raw = await idbGet(`komakun-project-${targetId}`);
        if (!raw) return;
        const data: ProjectState = JSON.parse(raw as string);
        set({
          projectId: data.projectId,
          projectName: data.projectName,
          pages: data.pages,
          activePageId: data.activePageId,
          starred: data.starred ?? false,
          lastEditedAt: data.lastEditedAt ?? null,
          createdAt: data.createdAt ?? null,
        });
      },

      deleteProject: async (targetId) => {
        const state = get();
        // Remove from IndexedDB & list
        await idbDel(`komakun-project-${targetId}`);
        useProjectsListStore.getState().removeProject(targetId);
        // If it's the active project, clear the store
        if (state.projectId === targetId) {
          set({ ...EMPTY_PROJECT });
        }
      },
    }),
    {
      name: "komakun-project",
      storage: createDebouncedPersistStorage(idbStorage, 1500),
      onRehydrateStorage: () => {
        return (state) => {
          // Migrate / register existing project in the projects list
          if (state?.projectId) {
            persistProjectToIDB(state);
            syncSummaryToList(state);
          }
        };
      },
    }
  )
);

// ── Auto-sync to list store on state changes (debounced) ──
let _syncTimer: ReturnType<typeof setTimeout> | null = null;
useProjectStore.subscribe((state) => {
  if (!state.projectId) return;
  if (_syncTimer) clearTimeout(_syncTimer);
  _syncTimer = setTimeout(() => {
    persistProjectToIDB(state);
    syncSummaryToList(state);
  }, 2000);
});
